### ISSUE TITLE
静音设置不好使

### ISSUE THREAD

**Issue by delingli** [WanAndroid/LiveWallPaper#2]
那个广播方式 设置是否静音好像不管用啊，你设置时候，里面的Entity实例还没创建呢onCreate方法都没执行接收不到的

**Comment by hongyangAndroid** [comment]
hi ~ 该项目是个群体学习的项目，不做维护呢。不过关于静音：你可以在通过SharedPreferences设置静音等相关配置，在onVisibleChange是读取设置状态。
